### ISSUE TITLE
Reporte de Práctica

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-entrevista-sistemhuerto#1]
Se debe subir el reporte de práctica

**Comment by Yabin-2021** [comment]
[S3GPS 01 - Práctica EDT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-entrevista-sistemhuerto/files/9854147/S3GPS.01.-.Practica.EDT.pdf)

**Comment by josealfredo79** [comment]
Favor de subir nuevamente el trabajo...

**Comment by Yabin-2021** [comment]
Si, lo subo

**Comment by Yabin-2021** [comment]
[S3GPS 01 - Práctica EDT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-entrevista-sistemhuerto/files/9946664/S3GPS.01.-.Practica.EDT.pdf)

Reporte Final

**Comment by Ferch0419** [comment]
Buen trabajo. Calificación: 30/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
